### ISSUE TITLE
UI improvement #1

### ISSUE THREAD

**Issue by ghost** [litentry/litentry-app#1021] opened 2022-03-22 08:19 UTC

**Comment by ghost** [comment] 2022-03-22 08:20
![Screenshot_20220321-115827.jpg](https://images.zenhubusercontent.com/61e6dbe5f12699478a956bb0/c6c957b8-2a60-40c3-8fa5-df720c1fe792)

**Comment by Ekaanth** [comment] 2022-03-22 17:37
@mikuczi unable to reproduce this UI issue. Can you help me provide mobile details? The attached image is a comparison of IOS and android.
<img width="746" alt="image" src="https://user-images.githubusercontent.com/22363352/159541290-32f8c4d5-aa69-4cba-a1ae-698ce98b2c10.png">

**Comment by ghost** [comment] 2022-03-23 11:05
I have reinstalled the application and this works fine

**Comment by Ekaanth** [comment] 2022-03-23 11:55
@mikuczi, can i close this ticket in that case?

**Comment by ghost** [comment] 2022-03-23 14:58
yups

**Comment by Ekaanth** [comment] 2022-03-23 16:25
> I have reinstalled the application and this works fine

Unable to reproduce in the latest version.

**Closed as completed by Ekaanth** 2022-03-23 16:25 UTC
