### ISSUE TITLE
UI improvement #3

### ISSUE THREAD

**Issue by ghost** [litentry/litentry-app#1023] opened 2022-03-22 08:26 UTC

**Comment by ghost** [comment] 2022-03-22 08:26
long text is getting out of the box 

![Screenshot_20220321-115453.jpg](https://images.zenhubusercontent.com/61e6dbe5f12699478a956bb0/6fde7e29-3ebc-4e15-ac61-95295aa387fb)

**Comment by Ekaanth** [comment] 2022-03-24 14:53
Currently unable to reproduce this issue due to the latest configuration of the `proposer.` If there is a change in the `ProposalCallInfo` account to add the account details, this can be revisited. The values seem to hold good within the card for the other sub calls.

**Comment by silva-fj** [comment] 2022-03-24 15:01
What do you mean by "latest configuration of the proposer"?

**Comment by Ekaanth** [comment] 2022-03-24 15:05
@franjs "Latest configuration of the proposer" means that we added the sub-call function to render the `proposal` was added with this [PR](https://github.com/litentry/litentry-app/pull/994). But I verified that the name-value from `proposalCallInfo` present in the card is wrapped when a large text is encountered.

**Comment by silva-fj** [comment] 2022-03-24 15:14
I see.. I didn't check that PR.

**Comment by Ekaanth** [comment] 2022-03-30 08:54
Blocked by https://github.com/litentry/litentry-app/issues/1003

**Comment by ishrak-imam** [comment] 2022-04-11 07:37
This should be fixed here https://github.com/litentry/litentry-app/pull/1053

**Comment by Ekaanth** [comment] 2022-04-12 14:11
Unable to reproduce this issue after the fix #1058

**Closed as completed by Ekaanth** 2022-04-12 14:12 UTC
